### ISSUE TITLE
how we update style

### ISSUE THREAD

**Issue by kilik128** [joshehlinger/wombo_extract#2]
# Don't forget to stay hydrated

**Comment by kilik128** [comment]
┌─────┬───────────────────┬─────────────────────────────────────────────────────────────────────────────────────────┬────────────┬────────────┬────────┐
│  id │              name │                                                                               photo_url │ is_premium │ model_type │ is_new │
├─────┼───────────────────┼─────────────────────────────────────────────────────────────────────────────────────────┼────────────┼────────────┼────────┤
│   1 │         Synthwave │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/synthwave.jpg │      false │      vqgan │  false │
│   2 │            Ukiyoe │                  https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/ukiyoe.jpg │      false │      vqgan │  false │
│   3 │          No Style │              https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/no-style-1.jpg │      false │      vqgan │  false │
│   4 │         Steampunk │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/steampunk.jpg │      false │      vqgan │  false │
│   5 │       Fantasy Art │             https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/fantasy-art.jpg │      false │      vqgan │  false │
│   6 │           Vibrant │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/vibrant.jpg │      false │      vqgan │  false │
│   7 │                HD │                      https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/hd.jpg │      false │      vqgan │  false │
│   9 │           Psychic │        https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/psychic-dystopia.jpg │      false │      vqgan │  false │
│  10 │      Dark Fantasy │            https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/dark-fantasy.jpg │      false │      vqgan │  false │
│  11 │          Mystical │              https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/mystical_2.jpg │      false │      vqgan │  false │
│  12 │           Festive │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/festive.jpeg │      false │      vqgan │  false │
│  14 │           Etching │             https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/etching_tn.jpeg │      false │      vqgan │  false │
│  16 │      Wuhtercuhler │              https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/watercolor.jpg │      false │      vqgan │  false │
│  17 │        Provenance │ https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/provenance-thumbnail-8.jpeg │      false │      vqgan │  false │
│  18 │         Rose Gold │    https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/rose-gold-thumbnail.jpeg │      false │      vqgan │  false │
│  22 │            Ghibli │                  https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/ghibli.jpg │      false │      vqgan │  false │
│  28 │       Melancholic │            https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/melancholic.jpeg │      false │      vqgan │  false │
│  31 │            Toasty │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/toasty.jpeg │      false │      vqgan │  false │
│  32 │         Realistic │              https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/realistic.jpeg │      false │  diffusion │  false │
│  34 │            Arcane │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/arcane.jpeg │      false │      vqgan │  false │
│  35 │         Throwback │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/throwback.jpg │      false │  diffusion │  false │
│  36 │          Daydream │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/daydream.jpeg │      false │      vqgan │  false │
│  37 │           Surreal │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/surreal.jpg │      false │  diffusion │  false │
│  38 │               Ink │                     https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/ink.png │      false │  diffusion │  false │
│  39 │           Pandora │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/pandora.jpeg │      false │      vqgan │  false │
│  40 │        Malevolent │             https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/malevolent.jpeg │      false │      vqgan │  false │
│  41 │        Street Art │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/streetart.jpg │      false │  diffusion │  false │
│  42 │       Unrealistic │            https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/unrealistic.jpeg │      false │  diffusion │  false │
│  45 │             Comic │                   https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/comic.png │      false │  diffusion │  false │
│  46 │             Anime │                   https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/anime.png │      false │  diffusion │  false │
│  47 │          Line-Art │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/lineart.png │      false │  diffusion │  false │
│  48 │           Gouache │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/gouache.png │      false │  diffusion │  false │
│  49 │           Polygon │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/polygon.png │      false │  diffusion │  false │
│  50 │             Paint │                   https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/paint.png │      false │  diffusion │  false │
│  51 │               VFX │                     https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/vfx.png │       true │  diffusion │  false │
│  52 │               HDR │                     https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/hdr.png │      false │  diffusion │  false │
│  53 │          Analogue │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/analogue.png │      false │  diffusion │  false │
│  54 │    Retro-Futurism │           https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/retrofuturism.png │      false │  diffusion │  false │
│  55 │         Isometric │              https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/isometric.jpeg │      false │  diffusion │  false │
│  56 │    Abstract Fluid │          https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/abstractfluid.jpeg │       true │  diffusion │  false │
│  57 │          Bad Trip │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/badtrip.jpeg │      false │  diffusion │  false │
│  58 │        Cartoonist │             https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/cartoonist.jpeg │      false │  diffusion │  false │
│  60 │            Vector │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/vector.jpeg │      false │  diffusion │  false │
│  61 │       Fantastical │            https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/fantastical.jpeg │      false │  diffusion │  false │
│  62 │          The City │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/thecity.jpeg │       true │  diffusion │  false │
│  63 │          Spectral │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/spectral.jpeg │      false │  diffusion │  false │
│  64 │          Dystopia │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/dystopia.jpeg │       true │  diffusion │  false │
│  65 │           Diorama │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/diorama.jpeg │      false │  diffusion │  false │
│  67 │          Abstract │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/abstract.jpeg │      false │  diffusion │  false │
│  68 │             Flora │                   https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/flora.png │      false │  diffusion │  false │
│  69 │        Watercolor │            https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/watercolor2.jpeg │       true │  diffusion │  false │
│  70 │      Illustrative │           https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/illustrative.jpeg │       true │  diffusion │  false │
│  71 │        Soft Touch │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/softtouch.png │      false │  diffusion │  false │
│  72 │            Winter │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/winter2.png │      false │  diffusion │  false │
│  73 │           Festive │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/festive2.png │      false │  diffusion │  false │
│  74 │          Splatter │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/splatter.png │      false │  diffusion │  false │
│  75 │       Flat Design │              https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/flatdesign.png │       true │  diffusion │  false │
│  76 │            Figure │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/figure.jpeg │      false │  diffusion │  false │
│  77 │     Expressionism │           https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/expressionism.png │      false │  diffusion │  false │
│  78 │      Realistic v2 │            https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/realistic_v2.jpg │      false │  diffusion │  false │
│  79 │            VFX v2 │         https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/vfxv2_thumbnail.jpg │       true │  diffusion │  false │
│  80 │          Anime v2 │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/animev2.jpg │      false │  diffusion │  false │
│  81 │          Flora v2 │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/floralv2.jpg │      false │  diffusion │  false │
│  82 │            HDR v2 │                   https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/hdrv2.jpg │       true │  diffusion │  false │
│  83 │  Expressionism v2 │          https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/expressionism2.png │      false │  diffusion │  false │
│  84 │   Buliojourney v2 │         https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/buliojourney_v2.jpg │      false │  diffusion │  false │
│  85 │      Rorschach v2 │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/rorschach.jpg │       true │  diffusion │  false │
│  86 │         Vector v2 │                https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/vectorv2.jpg │       true │  diffusion │  false │
│  87 │           Item v2 │                    https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/item.jpg │       true │  diffusion │  false │
│  88 │          Blues v2 │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/bluesv2.jpg │      false │  diffusion │  false │
│  89 │    Unrealistic v2 │            https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/photorealism.jpg │       true │  diffusion │  false │
│  90 │     Cartoonist v2 │           https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/cartoonist_v2.jpg │       true │  diffusion │  false │
│  91 │     Watercolor v2 │           https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/watercolor_v2.jpg │      false │  diffusion │  false │
│  92 │       Spectral v2 │              https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/spectralv2.jpg │      false │  diffusion │  false │
│  93 │         Spring v2 │                  https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/spring.jpg │       true │  diffusion │  false │
│  94 │            Gloomy │               https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/gloomy_v2.jpg │      false │  diffusion │  false │
│  95 │           The Cut │                 https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/the_cut.jpg │      false │  diffusion │  false │
│  96 │     The Bulio Cut │           https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/the_cut_bulio.jpg │      false │  diffusion │  false │
│  97 │      Dreamwave v2 │            https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/dreamwave_v2.jpg │      false │  diffusion │  false │
│  98 │    Illustrated v2 │             https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/illustrated.jpg │       true │  diffusion │  false │
│  99 │ Abstract Fluid v2 │       https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/abstract_fluid_v2.jpg │       true │  diffusion │  false │
│ 100 │            Ink v2 │                  https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/ink_v2.jpg │      false │  diffusion │  false │
│ 101 │        Poster Art │              https://d3j730xi5ph1dq.cloudfront.net/dream/style_thumbnail/poster_art.jpg │      false │  diffusion │   true │
└─────┴───────────────────┴─────────────────────────────────────────────────────────────────────────────────────────┴────────────┴────────────┴────────┘

**Comment by joshehlinger** [comment]
Thanks for this. Feel free to submit a PR to update the `STYLE` dictionary with any missing values
